import { BADGE_CHALLENGES as CHALLENGES } from "./badge-challenges.js";
const TEAM_NAMES = ["Team 1", "Team 2", "Team 3"];
const els = Object.fromEntries(["extraList", "extraConnection"].map(id => [id, document.getElementById(id)]));
const createDeviceId = () => { if (typeof crypto.randomUUID === "function") return crypto.randomUUID(); const bytes = crypto.getRandomValues(new Uint8Array(16)); bytes[6] = (bytes[6] & 15) | 64; bytes[8] = (bytes[8] & 63) | 128; const hex = [...bytes].map(byte => byte.toString(16).padStart(2, "0")).join(""); return `${hex.slice(0, 8)}-${hex.slice(8, 12)}-${hex.slice(12, 16)}-${hex.slice(16, 20)}-${hex.slice(20)}`; };
const deviceId = localStorage.getItem("claimChicagoDeviceId") || createDeviceId(); localStorage.setItem("claimChicagoDeviceId", deviceId);
let selectedTeam = localStorage.getItem("claimChicagoTeam") || "", completions = {}, specialClaims = {}, db = null, firebaseApi = null, firebaseUserId = null, selectedChallenge = null;
const map = L.map("extraMap", { zoomControl: false, minZoom: 10 }).setView([41.86, -87.64], 11); L.control.zoom({ position: "bottomright" }).addTo(map); L.tileLayer("https://tile.openstreetmap.org/{z}/{x}/{y}.png", { attribution: "&copy; <a href=\"https://www.openstreetmap.org/copyright\">OpenStreetMap</a> contributors", maxZoom: 19 }).addTo(map);
const markers = new Map(), colorFor = team => ({ "Team 1": "#e45745", "Team 2": "#3f7fc4", "Team 3": "#2f9a74" }[team] || "#718076"), completionFor = (team, id) => completions?.[team]?.[id], isMine = claim => db ? claim?.userId === firebaseUserId : claim?.deviceId === deviceId;

function renderTeams() { document.querySelectorAll("[data-team]").forEach(button => button.classList.toggle("selected", button.dataset.team === selectedTeam)); }
function markerIcon(challenge) { const claim = challenge.stealable ? specialClaims[challenge.id] : null, doneTeams = challenge.stealable ? [] : TEAM_NAMES.filter(team => completionFor(team, challenge.id)), ownTeam = claim?.owner || doneTeams.length === 1 ? doneTeams[0] : "", label = claim ? claim.owner.replace("Team ", "T") : doneTeams.length === 1 ? doneTeams[0].replace("Team ", "T") : doneTeams.length ? doneTeams.length + "T" : "○", color = claim ? colorFor(claim.owner) : doneTeams.length === 1 ? colorFor(doneTeams[0]) : doneTeams.length ? "#1f6b4b" : "#718076"; return L.divIcon({ className: "loop-marker-wrap", html: '<span class="loop-marker ' + (claim || doneTeams.length ? "claimed" : "") + '" style="--marker-color:' + color + '">' + label + '</span>', iconSize: [34, 34], iconAnchor: [17, 17] }); }
function statusChips(challenge) { return TEAM_NAMES.map(team => { const complete = challenge.stealable ? specialClaims[challenge.id]?.owner === team : !!completionFor(team, challenge.id); return '<span class="task-team-status ' + (complete ? "done" : "") + '" style="--team-color:' + colorFor(team) + '">' + team.replace("Team ", "T") + '</span>'; }).join(""); }
function renderChallenges() { els.extraList.innerHTML = CHALLENGES.map(challenge => { const selected = selectedChallenge === challenge.id ? " selected" : "", current = challenge.stealable ? specialClaims[challenge.id] : completionFor(selectedTeam, challenge.id), mine = isMine(current), reward = challenge.points === null ? "Reward TBD" : challenge.points + " pts"; let action = ""; if (challenge.stealable) { action = !selectedTeam ? "Choose a team" : !current ? "Claim record" : mine ? "Release record" : "Steal record"; } else action = current ? (mine ? "Undo" : "Completed") : "Confirm completion"; const disabled = !selectedTeam || (current && !mine && !challenge.stealable) ? " disabled" : ""; const owner = challenge.stealable && current ? "Held by " + current.owner : challenge.stealable ? "Open record" : "Team completion"; return '<article class="task-card extra-card' + selected + '"><button class="task-map-link" type="button" data-focus="' + challenge.id + '"><span class="task-completion-count">' + reward + '</span><span><strong>' + challenge.title + '</strong><small>' + challenge.detail + '</small></span></button><div class="challenge-meta"><span>' + owner + '</span><span class="task-team-statuses">' + statusChips(challenge) + '</span></div><div class="task-action"><small class="challenge-note">Physical visits and park spacing are confirmed on the honor system.</small><button class="task-toggle" type="button" data-challenge="' + challenge.id + '"' + disabled + '>' + action + '</button></div></article>'; }).join(""); }
function refreshMarkers() { CHALLENGES.forEach(challenge => markers.get(challenge.id)?.setIcon(markerIcon(challenge))); }
function refresh() { renderTeams(); renderChallenges(); refreshMarkers(); }
function setConnection(text) { els.extraConnection.textContent = text; }
function demoData() { completions = JSON.parse(localStorage.getItem("claimChicagoExtraCompletions") || "{}"); specialClaims = JSON.parse(localStorage.getItem("claimChicagoSpecialClaims") || "{}"); }
async function initFirebase() { const config = window.CLAIM_CHICAGO_FIREBASE_CONFIG; if (!config) { demoData(); setConnection("Demo mode · challenges stay on this device"); return; } try { const [appApi, dbApi, authApi] = await Promise.all([import("https://www.gstatic.com/firebasejs/10.12.5/firebase-app.js"), import("https://www.gstatic.com/firebasejs/10.12.5/firebase-database.js"), import("https://www.gstatic.com/firebasejs/10.12.5/firebase-auth.js")]); const app = appApi.initializeApp(config), credential = await authApi.signInAnonymously(authApi.getAuth(app)); firebaseUserId = credential.user.uid; db = dbApi.getDatabase(app); firebaseApi = dbApi; dbApi.onValue(dbApi.ref(db, "extraChallengeCompletions"), snapshot => { completions = snapshot.val() || {}; refresh(); setConnection("Live · challenge progress syncs instantly"); }, error => { console.error(error); db = null; firebaseApi = null; firebaseUserId = null; demoData(); refresh(); setConnection("Live connection failed · demo mode"); }); dbApi.onValue(dbApi.ref(db, "specialChallengeClaims"), snapshot => { specialClaims = snapshot.val() || {}; refresh(); }, error => { console.error(error); specialClaims = JSON.parse(localStorage.getItem("claimChicagoSpecialClaims") || "{}"); refresh(); }); } catch (error) { console.error(error); demoData(); setConnection("Connection failed · demo mode"); } }
async function updateCompletion(team, id, next) { if (db) { const result = await firebaseApi.runTransaction(firebaseApi.ref(db, `extraChallengeCompletions/${team}/${id}`), current => next === null ? (current?.userId === firebaseUserId ? null : undefined) : (current ? undefined : next)); if (!result.committed) throw new Error("This completion changed before it could be saved."); return; } if (next && completionFor(team, id)) throw new Error("This challenge is already complete for your team."); if (next === null && !isMine(completionFor(team, id))) throw new Error("Only the team member who completed it can undo it."); if (next === null) delete completions[team][id]; else { completions[team] ??= {}; completions[team][id] = next; } localStorage.setItem("claimChicagoExtraCompletions", JSON.stringify(completions)); }
async function updateSpecial(id, next) { if (db) { const result = await firebaseApi.runTransaction(firebaseApi.ref(db, `specialChallengeClaims/${id}`), current => next === null ? (current?.userId === firebaseUserId ? null : undefined) : next); if (!result.committed) throw new Error("That record changed before it could be saved."); return; } if (next === null && !isMine(specialClaims[id])) throw new Error("Only the current holder can release this record."); if (next === null) delete specialClaims[id]; else specialClaims[id] = next; localStorage.setItem("claimChicagoSpecialClaims", JSON.stringify(specialClaims)); }
CHALLENGES.forEach(challenge => { const marker = L.marker(challenge.coordinates, { icon: markerIcon(challenge) }).addTo(map).bindTooltip(challenge.title, { direction: "top" }); markers.set(challenge.id, marker); marker.on("click", () => { selectedChallenge = challenge.id; renderChallenges(); document.querySelector(`[data-focus="${challenge.id}"]`)?.scrollIntoView({ behavior: "smooth", block: "nearest" }); }); });
document.addEventListener("click", async event => { const teamButton = event.target.closest("[data-team]"); if (teamButton) { selectedTeam = teamButton.dataset.team; localStorage.setItem("claimChicagoTeam", selectedTeam); refresh(); return; } const focus = event.target.closest("[data-focus]"); if (focus) { const challenge = CHALLENGES.find(item => item.id === focus.dataset.focus); selectedChallenge = challenge.id; map.flyTo(challenge.coordinates, 13, { duration: .45 }); renderChallenges(); return; } const button = event.target.closest("[data-challenge]"); if (!button || !selectedTeam) return; const challenge = CHALLENGES.find(item => item.id === button.dataset.challenge), timestamp = Date.now(); button.disabled = true; try { if (challenge.stealable) { const current = specialClaims[challenge.id]; await updateSpecial(challenge.id, current && isMine(current) ? null : { owner: selectedTeam, deviceId, userId: firebaseUserId, completedAt: timestamp }); } else { const current = completionFor(selectedTeam, challenge.id); await updateCompletion(selectedTeam, challenge.id, current ? null : { owner: selectedTeam, deviceId, userId: firebaseUserId, completedAt: timestamp }); } } catch (error) { setConnection(error.message); } finally { refresh(); } });
refresh(); setConnection("Connecting to live challenge progress…"); await initFirebase(); refresh();
