const TEAM_NAMES=["Team 1","Team 2","Team 3"];
const REQUIRED_TASKS=3;
const TASKS=[
  {id:"cloud-gate",title:"Meet at Cloud Gate",detail:"Gather your crew at Millennium Park's mirrored landmark.",coordinates:[41.8826,-87.6233]},
  {id:"cultural-center",title:"Explore the Cultural Center",detail:"Find a mosaic, dome, or exhibition worth sharing.",coordinates:[41.8839,-87.6247]},
  {id:"riverwalk",title:"Walk the Riverwalk",detail:"Complete a stretch between State Street and Michigan Avenue.",coordinates:[41.8881,-87.6274]},
  {id:"state-street",title:"State Street mission",detail:"City .",coordinates:[41.8847,-87.6272]},
  {id:"theatre-district",title:"I finally made it!",detail:"Upon arriving at a marquee in Chicago's Theatre District sing one show tune for one minute",coordinates:[41.8843,-87.6287]},
  {id:"art-institute",title:"Art Institute stop",detail:"At the art insitute, take out your phone and draw your favorite animal for 1 minute. Your teammate must guess the animal you drew",coordinates:[41.8796,-87.6237]},
  {id:"willis-tower",title:"In the Clouds",detail:"Go to the Willis Tower Skydeck and take a selfie with your teammate in the glass box. (Cannot be used for height badge)",coordinates:[41.8789,-87.6359]},
  {id:"Pedway",title:"Lower Wacker of Walking",detail:"Near Macy's on state street enter the pedway below the city. Walk for at least 5 minutes or till you find a train, food, some sort of art piece" ,coordinates:[41.8838, -87.6279]}
];
const els=Object.fromEntries(["taskList","teamCounters","loopConnection"].map(id=>[id,document.getElementById(id)]));
const createDeviceId=()=>{if(typeof crypto.randomUUID==="function")return crypto.randomUUID();const bytes=crypto.getRandomValues(new Uint8Array(16));bytes[6]=(bytes[6]&15)|64;bytes[8]=(bytes[8]&63)|128;const hex=[...bytes].map(byte=>byte.toString(16).padStart(2,"0")).join("");return `${hex.slice(0,8)}-${hex.slice(8,12)}-${hex.slice(12,16)}-${hex.slice(16,20)}-${hex.slice(20)}`;};
const deviceId=localStorage.getItem("claimChicagoDeviceId")||createDeviceId();localStorage.setItem("claimChicagoDeviceId",deviceId);
let selectedTeam=localStorage.getItem("claimChicagoTeam")||"",completions={},db=null,firebaseApi=null,firebaseUserId=null,selectedTask=null;
const map=L.map("loopMap",{zoomControl:false,minZoom:12}).setView([41.8835,-87.6285],14);L.control.zoom({position:"bottomright"}).addTo(map);L.tileLayer("https://tile.openstreetmap.org/{z}/{x}/{y}.png",{attribution:"&copy; <a href=\"https://www.openstreetmap.org/copyright\">OpenStreetMap</a> contributors",maxZoom:19}).addTo(map);
const markers=new Map(),colorFor=team=>({"Team 1":"#e45745","Team 2":"#3f7fc4","Team 3":"#2f9a74"}[team]||"#718076"),claimFor=(team,id)=>completions?.[team]?.[id],mine=claim=>db?claim?.userId===firebaseUserId:claim?.deviceId===deviceId,countFor=team=>Object.keys(completions?.[team]||{}).length;
function renderTeams(){document.querySelectorAll("[data-team]").forEach(button=>button.classList.toggle("selected",button.dataset.team===selectedTeam));}
function markerIcon(task){const doneBy=TEAM_NAMES.filter(team=>claimFor(team,task.id)),ownTeam=selectedTeam&&doneBy.includes(selectedTeam),label=ownTeam?"✓":doneBy.length===1?doneBy[0].replace("Team ","T"):doneBy.length?doneBy.length+"T":"○",color=ownTeam?colorFor(selectedTeam):doneBy.length===1?colorFor(doneBy[0]):doneBy.length?"#1f6b4b":"#718076";return L.divIcon({className:"loop-marker-wrap",html:'<span class="loop-marker '+(doneBy.length?"claimed":"")+'" style="--marker-color:'+color+'">'+label+'</span>',iconSize:[34,34],iconAnchor:[17,17]});}
function renderCounters(){els.teamCounters.innerHTML=TEAM_NAMES.map(team=>{const count=countFor(team),ready=count>=REQUIRED_TASKS;return '<div class="team-counter '+(ready?"ready":"")+'"><span class="team-counter-dot" style="background:'+colorFor(team)+'"></span><span><strong>'+team+'</strong><small>'+count+' / '+REQUIRED_TASKS+' complete · '+(ready?"Neighborhoods unlocked":"Keep going")+'</small></span></div>';}).join("");}
function renderTasks(){els.taskList.innerHTML=TASKS.map(task=>{const current=selectedTeam&&claimFor(selectedTeam,task.id),isMine=mine(current),doneBy=TEAM_NAMES.filter(team=>claimFor(team,task.id)),completionLabel=!doneBy.length?"Available":doneBy.length===1?doneBy[0]+" complete":doneBy.length+" teams complete";const status=TEAM_NAMES.map(team=>'<span class="task-team-status '+(claimFor(team,task.id)?"done":"")+'" style="--team-color:'+colorFor(team)+'" title="'+team+(claimFor(team,task.id)?" completed":" not completed")+'">'+team.replace("Team ","T")+'</span>').join("");const disabled=!selectedTeam||(current&&!isMine)?" disabled":"";const action=current?(isMine?"Undo":"Completed"):"Complete task";const selected=selectedTask===task.id?" selected":"";return '<article class="task-card'+selected+'"><button class="task-map-link" type="button" data-focus="'+task.id+'"><span class="task-completion-count">'+completionLabel+'</span><span><strong>'+task.title+'</strong><small>'+task.detail+'</small></span></button><div class="task-action"><span class="task-team-statuses">'+status+'</span><button class="task-toggle" type="button" data-task="'+task.id+'"'+disabled+'>'+action+'</button></div></article>';}).join("");}
function refreshMarkers(){TASKS.forEach(task=>markers.get(task.id)?.setIcon(markerIcon(task)));}
function refresh(){renderTeams();renderCounters();renderTasks();refreshMarkers();}
function setConnection(text){els.loopConnection.textContent=text;}
async function initFirebase(){const config=window.CLAIM_CHICAGO_FIREBASE_CONFIG;if(!config){completions=JSON.parse(localStorage.getItem("claimChicagoLoopCompletions")||"{}");setConnection("Demo mode · tasks stay on this device");return;}try{const [appApi,dbApi,authApi]=await Promise.all([import("https://www.gstatic.com/firebasejs/10.12.5/firebase-app.js"),import("https://www.gstatic.com/firebasejs/10.12.5/firebase-database.js"),import("https://www.gstatic.com/firebasejs/10.12.5/firebase-auth.js")]);const app=appApi.initializeApp(config),credential=await authApi.signInAnonymously(authApi.getAuth(app));firebaseUserId=credential.user.uid;db=dbApi.getDatabase(app);firebaseApi=dbApi;dbApi.onValue(dbApi.ref(db,"loopTaskCompletions"),snapshot=>{completions=snapshot.val()||{};refresh();setConnection("Live · team progress syncs instantly");},error=>{console.error(error);db=null;firebaseApi=null;firebaseUserId=null;completions=JSON.parse(localStorage.getItem("claimChicagoLoopCompletions")||"{}");refresh();setConnection("Live connection failed · demo mode");});}catch(error){console.error(error);completions=JSON.parse(localStorage.getItem("claimChicagoLoopCompletions")||"{}");setConnection("Connection failed · demo mode");}}
async function updateTask(team,id,next){if(db){const result=await firebaseApi.runTransaction(firebaseApi.ref(db,`loopTaskCompletions/${team}/${id}`),current=>next===null?(current?.userId===firebaseUserId?null:undefined):(current?undefined:next));if(!result.committed)throw new Error("This task was already completed for your team.");return;}if(next&&claimFor(team,id))throw new Error("This task is already completed for your team.");if(next===null&&!mine(claimFor(team,id)))throw new Error("Only the player who completed this task can undo it.");if(next===null)delete completions[team][id];else{completions[team]??={};completions[team][id]=next;}localStorage.setItem("claimChicagoLoopCompletions",JSON.stringify(completions));refresh();}
TASKS.forEach(task=>{const marker=L.marker(task.coordinates,{icon:markerIcon(task)}).addTo(map).bindTooltip(task.title,{direction:"top"});markers.set(task.id,marker);marker.on("click",()=>{selectedTask=task.id;renderTasks();document.querySelector(`[data-focus="${task.id}"]`)?.scrollIntoView({behavior:"smooth",block:"nearest"});});});
document.addEventListener("click",async event=>{const teamButton=event.target.closest("[data-team]");if(teamButton){selectedTeam=teamButton.dataset.team;localStorage.setItem("claimChicagoTeam",selectedTeam);refresh();return;}const focusButton=event.target.closest("[data-focus]");if(focusButton){const task=TASKS.find(item=>item.id===focusButton.dataset.focus);selectedTask=task.id;map.flyTo(task.coordinates,16,{duration:.45});renderTasks();return;}const toggle=event.target.closest("[data-task]");if(!toggle)return;const id=toggle.dataset.task,current=claimFor(selectedTeam,id);toggle.disabled=true;try{await updateTask(selectedTeam,id,current?null:{owner:selectedTeam,deviceId,userId:firebaseUserId,completedAt:Date.now()});}catch(error){setConnection(error.message);}finally{refresh();}});
refresh();
setConnection("Connecting to live team progress…");
await initFirebase();
refresh();
