const TASKS=[
  {id:"cloud-gate",title:"Meet at Cloud Gate",detail:"Gather your crew at Millennium Park's mirrored landmark.",points:2,coordinates:[41.8826,-87.6233]},
  {id:"cultural-center",title:"Explore the Cultural Center",detail:"Find a mosaic, dome, or exhibition worth sharing.",points:3,coordinates:[41.8839,-87.6247]},
  {id:"riverwalk",title:"Walk the Riverwalk",detail:"Complete a stretch between State Street and Michigan Avenue.",points:2,coordinates:[41.8881,-87.6274]},
  {id:"state-street",title:"State Street mission",detail:"Visit a local business or landmark along State Street.",points:3,coordinates:[41.8847,-87.6272]},
  {id:"theatre-district",title:"Find the theater lights",detail:"Visit a marquee in Chicago's Theatre District.",points:2,coordinates:[41.8843,-87.6287]},
  {id:"art-institute",title:"Art Institute stop",detail:"Take in a favorite work or the lion statues outside.",points:3,coordinates:[41.8796,-87.6237]},
  {id:"willis-tower",title:"Look up at Willis Tower",detail:"Reach the tower plaza and record your team visit.",points:4,coordinates:[41.8789,-87.6359]}
];
const els=Object.fromEntries(["taskList","completedCount","taskCount","loopConnection"].map(id=>[id,document.getElementById(id)]));
const createDeviceId=()=>{if(typeof crypto.randomUUID==="function")return crypto.randomUUID();const bytes=crypto.getRandomValues(new Uint8Array(16));bytes[6]=(bytes[6]&15)|64;bytes[8]=(bytes[8]&63)|128;const hex=[...bytes].map(byte=>byte.toString(16).padStart(2,"0")).join("");return `${hex.slice(0,8)}-${hex.slice(8,12)}-${hex.slice(12,16)}-${hex.slice(16,20)}-${hex.slice(20)}`;};
const deviceId=localStorage.getItem("claimChicagoDeviceId")||createDeviceId();localStorage.setItem("claimChicagoDeviceId",deviceId);
let selectedTeam=localStorage.getItem("claimChicagoTeam")||"",taskClaims={},db=null,firebaseApi=null,firebaseUserId=null,selectedTask=null;
const map=L.map("loopMap",{zoomControl:false,minZoom:12}).setView([41.8835,-87.6285],14);L.control.zoom({position:"bottomright"}).addTo(map);L.tileLayer("https://tile.openstreetmap.org/{z}/{x}/{y}.png",{attribution:"&copy; <a href=\"https://www.openstreetmap.org/copyright\">OpenStreetMap</a> contributors",maxZoom:19}).addTo(map);
const markers=new Map(),colorFor=team=>({"Team 1":"#e45745","Team 2":"#3f7fc4","Team 3":"#2f9a74"}[team]||"#718076"),mine=claim=>db?claim?.userId===firebaseUserId:claim?.deviceId===deviceId;
function renderTeams(){document.querySelectorAll("[data-team]").forEach(button=>button.classList.toggle("selected",button.dataset.team===selectedTeam));}
function markerIcon(task){const claim=taskClaims[task.id],state=claim?" claimed":"",color=claim?colorFor(claim.owner):"#1f6b4b",label=claim?"✓":task.points;return L.divIcon({className:"loop-marker-wrap",html:'<span class="loop-marker'+state+'" style="--marker-color:'+color+'">'+label+'</span>',iconSize:[34,34],iconAnchor:[17,17]});}
function refreshMarkers(){TASKS.forEach(task=>markers.get(task.id)?.setIcon(markerIcon(task)));}
function renderTasks(){els.completedCount.textContent=Object.keys(taskClaims).length;els.taskCount.textContent=TASKS.length;els.taskList.innerHTML=TASKS.map(task=>{const claim=taskClaims[task.id],isMine=mine(claim),locked=claim&&!isMine,owner=claim?'<span class="task-owner"><i style="background:'+colorFor(claim.owner)+'"></i>'+(isMine?"Your team":claim.owner)+'</span>':'<span class="task-owner available">Available</span>',disabled=locked||(!claim&&!selectedTeam)?" disabled":"",action=isMine?"Unclaim":claim?"Claimed":"Claim task",selected=selectedTask===task.id?" selected":"";return '<article class="task-card'+selected+'"><button class="task-map-link" type="button" data-focus="'+task.id+'"><span class="task-points">'+task.points+' pts</span><span><strong>'+task.title+'</strong><small>'+task.detail+'</small></span></button><div class="task-action">'+owner+'<button class="task-toggle" type="button" data-task="'+task.id+'"'+disabled+'>'+action+'</button></div></article>';}).join("");}
function refresh(){renderTeams();renderTasks();refreshMarkers();}
function setConnection(text){els.loopConnection.textContent=text;}
async function initFirebase(){const config=window.CLAIM_CHICAGO_FIREBASE_CONFIG;if(!config){taskClaims=JSON.parse(localStorage.getItem("claimChicagoLoopTasks")||"{}");setConnection("Demo mode · tasks stay on this device");return;}try{const [appApi,dbApi,authApi]=await Promise.all([import("https://www.gstatic.com/firebasejs/10.12.5/firebase-app.js"),import("https://www.gstatic.com/firebasejs/10.12.5/firebase-database.js"),import("https://www.gstatic.com/firebasejs/10.12.5/firebase-auth.js")]);const app=appApi.initializeApp(config),credential=await authApi.signInAnonymously(authApi.getAuth(app));firebaseUserId=credential.user.uid;db=dbApi.getDatabase(app);firebaseApi=dbApi;dbApi.onValue(dbApi.ref(db,"loopTasks"),snapshot=>{taskClaims=snapshot.val()||{};refresh();setConnection("Live · task claims sync instantly");},error=>{console.error(error);db=null;firebaseApi=null;firebaseUserId=null;taskClaims=JSON.parse(localStorage.getItem("claimChicagoLoopTasks")||"{}");refresh();setConnection("Live connection failed · demo mode");});}catch(error){console.error(error);taskClaims=JSON.parse(localStorage.getItem("claimChicagoLoopTasks")||"{}");setConnection("Connection failed · demo mode");}}
async function updateTask(id,next){if(db){const result=await firebaseApi.runTransaction(firebaseApi.ref(db,`loopTasks/${id}`),current=>next===null?(current?.userId===firebaseUserId?null:undefined):(current?undefined:next));if(!result.committed)throw new Error("That task was just claimed by another team.");return;}if(next&&taskClaims[id])throw new Error("That task is already claimed.");if(next===null&&!mine(taskClaims[id]))throw new Error("Only the claiming team can unclaim this task.");if(next===null)delete taskClaims[id];else taskClaims[id]=next;localStorage.setItem("claimChicagoLoopTasks",JSON.stringify(taskClaims));refresh();}
TASKS.forEach(task=>{const marker=L.marker(task.coordinates,{icon:markerIcon(task)}).addTo(map).bindTooltip(task.title,{direction:"top"});markers.set(task.id,marker);marker.on("click",()=>{selectedTask=task.id;renderTasks();document.querySelector(`[data-focus="${task.id}"]`)?.scrollIntoView({behavior:"smooth",block:"nearest"});});});
document.addEventListener("click",async event=>{const teamButton=event.target.closest("[data-team]");if(teamButton){selectedTeam=teamButton.dataset.team;localStorage.setItem("claimChicagoTeam",selectedTeam);refresh();return;}const focusButton=event.target.closest("[data-focus]");if(focusButton){const task=TASKS.find(item=>item.id===focusButton.dataset.focus);selectedTask=task.id;map.flyTo(task.coordinates,16,{duration:.45});renderTasks();return;}const toggle=event.target.closest("[data-task]");if(!toggle)return;const id=toggle.dataset.task,claim=taskClaims[id];toggle.disabled=true;try{await updateTask(id,claim?null:{owner:selectedTeam,deviceId,userId:firebaseUserId,completedAt:Date.now()});}catch(error){setConnection(error.message);}finally{refresh();}});
await initFirebase();refresh();
