// Exact neighborhood scores from Column B of chicago_neighborhood_points_rated.xlsx.
export const NEIGHBORHOOD_POINTS = {
  "Albany Park": 7,
  "Andersonville": 6,
  "Arcadia Terrace": 7,
  "Archer Heights": 6,
  "Armour Square": 3,
  "Ashburn": 8,
  "Auburn Gresham": 7,
  "Avondale": 5,
  "Back of The Yards": 5,
  "Belmont Central": 6,
  "Belmont Gardens": 6,
  "Belmont Heights": 7,
  "Belmont Terrace": 7,
  "Beverly": 8,
  "Beverly View": 8,
  "Beverly Woods": 9,
  "Big Oaks": 9,
  "Bowmanville": 7,
  "Bridgeport": 4,
  "Brighton Park": 5,
  "Bronzeville": 3,
  "Brynford Park": 7,
  "Bucktown": 4,
  "Budlong Woods": 7,
  "Buena Park": 6,
  "Burnside": 7,
  "Calumet Heights": 7,
  "Canaryville": 6,
  "Chatham": 7,
  "Chicago Lawn": 6,
  "Chinatown": 3,
  "Chrysler Village": 8,
  "Clearing": 7,
  "Cottage Grove Heights": 7,
  "Cragin": 6,
  "Dearborn Park": 1,
  "Downtown Chicago / Loop": 1,
  "Dunning": 7,
  "East Garfield Park": 5,
  "East Rogers Park": 7,
  "East Side": 9,
  "East Village": 3,
  "Edgebrook": 8,
  "Edgewater": 6,
  "Edison Park": 9,
  "Englewood": 6,
  "Ford City": 8,
  "Fuller Park": 4,
  "Fulton Market District": 2,
  "Fulton River District": 2,
  "Gage Park": 6,
  "Garfield Ridge": 7,
  "Gladstone Park": 8,
  "Gold Coast": 3,
  "Goose Island": 3,
  "Grand Crossing": 6,
  "Greater Grand Crossing": 6,
  "Greektown": 2,
  "Hamlin Park Neighbors": 5,
  "Hanson Park": 7,
  "Hegewisch": 9,
  "Hermosa": 6,
  "Hollywood Park": 7,
  "Humboldt Park": 4,
  "Hyde Park": 5,
  "Ida B. Wells / Darrow Homes": 4,
  "IL Medical District": 2,
  "Irving Park": 5,
  "Irving Woods": 9,
  "Jefferson Park": 8,
  "Kelvyn Park": 6,
  "Kennedy Park": 9,
  "Kenwood": 4,
  "Kilbourn Park": 6,
  "Lakeview": 5,
  "Lakewood-Balmoral": 7,
  "Lawndale": 5,
  "LeClaire Courts": 8,
  "Lincoln Park": 4,
  "Lincoln Square": 6,
  "Little Village": 5,
  "Logan Square": 4,
  "Magnolia Glen": 7,
  "Marquette Park": 7,
  "Marycrest": 8,
  "Mayfair": 7,
  "Mckinley Park": 4,
  "Montclare": 7,
  "Morgan Park": 9,
  "Motor Row District": 2,
  "Mount Greenwood": 9,
  "Near North": 2,
  "New East Side": 1,
  "Noble Square": 3,
  "Northalsted": 5,
  "North Austin": 7,
  "North Branch Industrial Corridor": 4,
  "North Center": 5,
  "North Kenwood": 4,
  "North Mayfair": 7,
  "North Park": 7,
  "Norwood Park East": 8,
  "Norwood Park West": 9,
  "Oakland": 4,
  "O'Hare": 10,
  "Old Edgebrook": 8,
  "Old Irving Park": 6,
  "Old Norwood Park": 9,
  "Old Town": 3,
  "Old Town Triangle": 3,
  "Oriole Park": 8,
  "Palmer Square": 4,
  "Parkview": 8,
  "Park West": 4,
  "Peterson Park": 8,
  "Pilsen": 3,
  "Portage Park": 7,
  "Prairie District": 2,
  "Prairie Shores": 3,
  "Printer's Row": 1,
  "Pulaski Park": 5,
  "Pullman": 8,
  "Ranch Triangle": 4,
  "Ravenswood": 6,
  "Riverdale": 8,
  "River North": 2,
  "Rivers Edge": 9,
  "River West": 3,
  "Roscoe Village": 5,
  "Roseland": 8,
  "Sauganash": 8,
  "Sauganash Woods": 8,
  "Schorsch Forest View": 9,
  "Schorsch Village": 9,
  "Scottdale": 8,
  "Sheffield Neighbors": 4,
  "Sheridan Park": 6,
  "Sleepy Hollow": 9,
  "South Austin": 7,
  "South Chicago": 8,
  "South Deering": 8,
  "South Edgebrook": 8,
  "South Loop": 2,
  "South Old Irving Park": 5,
  "South Shore": 7,
  "Southport Corridor": 5,
  "Streeterville": 2,
  "The Gap / Douglas": 3,
  "The Villa District": 6,
  "Tri-Taylor": 3,
  "Ukrainian Village": 4,
  "Union Ridge": 9,
  "United Center Park": 3,
  "University Village / Little Italy": 3,
  "Uptown": 6,
  "Vittum Park": 7,
  "Washington Heights": 8,
  "Washington Park": 5,
  "West Beverly": 8,
  "West DePaul": 4,
  "West Englewood": 6,
  "West Garfield Park": 5,
  "West Humboldt Park": 6,
  "West Lawn": 7,
  "West Loop": 2,
  "West Morgan Park": 9,
  "West Pullman": 8,
  "West Rogers Park": 7,
  "West Woodlawn": 6,
  "Wicker Park": 4,
  "Wildwood": 9,
  "Winneconna Parkway": 9,
  "Woodlawn": 6,
  "Wrightwood": 8,
  "Wrightwood Neighbors": 8,
  "Wrigleyville": 5,
};
