// Districts imported from the Claim Chicago Google My Maps KML source.
// New districts start at 3 points; scores from the former community-area game
// are retained where the district name matches.
const DISTRICT_NAMES = [
  "Albany Park","Andersonville","Arcadia Terrace","Archer Heights","Armour Square","Ashburn","Auburn Gresham","Avondale","Back of The Yards","Belmont Central","Belmont Gardens","Belmont Heights","Belmont Terrace","Beverly","Beverly View","Beverly Woods","Big Oaks","Bowmanville","Bridgeport","Brighton Park","Bronzeville","Brynford Park","Bucktown","Budlong Woods","Buena Park","Burnside","Calumet Heights","Canaryville","Chatham","Chicago Lawn","Chinatown","Chrysler Village","Clearing","Cottage Grove Heights","Cragin","Dearborn Park","Downtown Chicago / Loop","Dunning","East Garfield Park","East Rogers Park","East Side","East Village","Edgebrook","Edgewater","Edison Park","Englewood","Ford City","Fuller Park","Fulton Market District","Fulton River District","Gage Park","Garfield Ridge","Gladstone Park","Gold Coast","Goose Island","Grand Crossing","Greater Grand Crossing","Greektown","Hamlin Park Neighbors","Hanson Park","Hegewisch","Hermosa","Hollywood Park","Humboldt Park","Hyde Park","Ida B. Wells / Darrow Homes","IL Medical District","Irving Park","Irving Woods","Jefferson Park","Kelvyn Park","Kennedy Park","Kenwood","Kilbourn Park","Lakeview","Lakewood-Balmoral","Lawndale","LeClaire Courts","Lincoln Park","Lincoln Square","Little Village","Logan Square","Magnolia Glen","Marquette Park","Marycrest","Mayfair","Mckinley Park","Montclare","Morgan Park","Motor Row District","Mount Greenwood","Near North","New East Side","Noble Square","Northalsted","North Austin","North Branch Industrial Corridor","North Center","North Kenwood","North Mayfair","North Park","Norwood Park East","Norwood Park West","Oakland","O'Hare","Old Edgebrook","Old Irving Park","Old Norwood Park","Old Town","Old Town Triangle","Oriole Park","Palmer Square","Parkview","Park West","Peterson Park","Pilsen","Portage Park","Prairie District","Prairie Shores","Printer's Row","Pulaski Park","Pullman","Ranch Triangle","Ravenswood","Riverdale","River North","Rivers Edge","River West","Roscoe Village","Roseland","Sauganash","Sauganash Woods","Schorsch Forest View","Schorsch Village","Scottdale","Sheffield Neighbors","Sheridan Park","Sleepy Hollow","South Austin","South Chicago","South Deering","South Edgebrook","South Loop","South Old Irving Park","South Shore","Southport Corridor","Streeterville","The Gap / Douglas","The Villa District","Tri-Taylor","Ukrainian Village","Union Ridge","United Center Park","University Village / Little Italy","Uptown","Vittum Park","Washington Heights","Washington Park","West Beverly","West DePaul","West Englewood","West Garfield Park","West Humboldt Park","West Lawn","West Loop","West Morgan Park","West Pullman","West Rogers Park","West Woodlawn","Wicker Park","Wildwood","Winneconna Parkway","Woodlawn","Wrightwood","Wrightwood Neighbors","Wrigleyville"
];

export const NEIGHBORHOOD_POINTS = Object.fromEntries(DISTRICT_NAMES.map(name=>[name,3]));

Object.assign(NEIGHBORHOOD_POINTS,{
  "Albany Park":4,"Archer Heights":4,"Armour Square":2,"Ashburn":5,"Auburn Gresham":5,"Avondale":3,"Beverly":5,"Bridgeport":2,"Brighton Park":3,"Burnside":5,"Calumet Heights":5,"Chatham":4,"Chicago Lawn":4,"Clearing":5,"Dunning":5,"East Garfield Park":2,"East Side":5,"Edgewater":4,"Edison Park":5,"Englewood":4,"Fuller Park":3,"Gage Park":4,"Garfield Ridge":5,"Greater Grand Crossing":4,"Hegewisch":5,"Hermosa":4,"Humboldt Park":3,"Hyde Park":3,"Irving Park":3,"Jefferson Park":4,"Kenwood":3,"Lincoln Park":2,"Lincoln Square":3,"Logan Square":3,"Mckinley Park":3,"Montclare":5,"Morgan Park":5,"Mount Greenwood":5,"North Center":3,"North Park":4,"Oakland":3,"O'Hare":5,"Portage Park":4,"Pullman":5,"Riverdale":5,"Roseland":5,"South Chicago":5,"South Deering":5,"South Shore":4,"Uptown":3,"Washington Heights":5,"Washington Park":3,"West Englewood":5,"West Garfield Park":3,"West Lawn":5,"West Pullman":5,"Woodlawn":4
});
